# Generated by Django 5.2.7 on 2025-10-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_category_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
